// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'app_error.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `classify_string`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `eq`, `fmt`, `fmt`, `from`
// These functions are ignored (category: IgnoreBecauseExplicitAttribute): `classify_anyhow`, `classify_display`, `from_display`, `other`

@freezed
sealed class EcashAppError with _$EcashAppError {
  const EcashAppError._();

  const factory EcashAppError.expiredInvoice() = EcashAppError_ExpiredInvoice;
  const factory EcashAppError.insufficientBalance({
    required BigInt neededMsats,
    required BigInt haveMsats,
  }) = EcashAppError_InsufficientBalance;
  const factory EcashAppError.noRouteFound() = EcashAppError_NoRouteFound;
  const factory EcashAppError.gatewayOffline() = EcashAppError_GatewayOffline;
  const factory EcashAppError.noGatewaysAvailable() =
      EcashAppError_NoGatewaysAvailable;
  const factory EcashAppError.federationOffline() =
      EcashAppError_FederationOffline;
  const factory EcashAppError.invalidInvoice(String field0) =
      EcashAppError_InvalidInvoice;
  const factory EcashAppError.invalidAddress(String field0) =
      EcashAppError_InvalidAddress;
  const factory EcashAppError.paymentRefunded(String field0) =
      EcashAppError_PaymentRefunded;
  const factory EcashAppError.timeout() = EcashAppError_Timeout;
  const factory EcashAppError.other(String field0) = EcashAppError_Other;
}
