// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'multimint.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OOBNotesDecoder>>
abstract class OobNotesDecoder implements RustOpaqueInterface {
  OobNotesWrapper? addFragment({required String fragment});

  factory OobNotesDecoder() =>
      RustLib.instance.api.crateFountainOobNotesDecoderNew();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OOBNotesEncoder>>
abstract class OobNotesEncoder implements RustOpaqueInterface {
  factory OobNotesEncoder({required OobNotesWrapper notes}) =>
      RustLib.instance.api.crateFountainOobNotesEncoderNew(notes: notes);

  Future<String> nextFragment();
}
