// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `strict_uri_encode`

LnurlWrapper? parseLnurl({required String request}) =>
    RustLib.instance.api.crateLnurlParseLnurl(request: request);

Future<PayResponseWrapper> lnurlFetchLimits({required LnurlWrapper lnurl}) =>
    RustLib.instance.api.crateLnurlLnurlFetchLimits(lnurl: lnurl);

Future<String> lnurlResolve({
  required PayResponseWrapper payResponse,
  required PlatformInt64 amountSats,
}) => RustLib.instance.api.crateLnurlLnurlResolve(
  payResponse: payResponse,
  amountSats: amountSats,
);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PayResponseWrapper>>
abstract class PayResponseWrapper implements RustOpaqueInterface {
  bool isFixedAmount();

  PlatformInt64 get maxSats;

  PlatformInt64 get minSats;
}

class LnurlWrapper {
  final String field0;

  const LnurlWrapper({required this.field0});

  String encode() =>
      RustLib.instance.api.crateLnurlLnurlWrapperEncode(that: this);

  @override
  int get hashCode => field0.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is LnurlWrapper &&
          runtimeType == other.runtimeType &&
          field0 == other.field0;
}
