// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `parse_content`, `parse_federation_id`, `parse_federation_name`, `parse_invite_codes`, `parse_modules`, `parse_network`, `parse_picture`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `fmt`, `try_from`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<NostrClient>>
abstract class NostrClient implements RustOpaqueInterface {
  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<NostrClient> newInstance({required Database db}) =>
      RustLib.instance.api.crateNostrNostrClientNew(db: db);

  Future<void> updateFederationsFromNostr();
}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<PublicFederation>>
abstract class PublicFederation implements RustOpaqueInterface {
  String? get about;

  FederationId get federationId;

  String get federationName;

  List<String> get inviteCodes;

  List<String> get modules;

  String get network;

  String? get picture;

  set about(String? about);

  set federationId(FederationId federationId);

  set federationName(String federationName);

  set inviteCodes(List<String> inviteCodes);

  set modules(List<String> modules);

  set network(String network);

  set picture(String? picture);
}
