// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.9.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import 'frb_generated.dart';
import 'lib.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `monitor_deposit_address`, `watch_pegin_address`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<ClientHandleArc>>
abstract class ClientHandleArc implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<UnboundedReceiver < (FederationId , TweakIdx) >>>
abstract class UnboundedReceiverFederationIdTweakIdx
    implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<WalletHandler>>
abstract class WalletHandler implements RustOpaqueInterface {
  Future<(String, BigInt)> allocateDepositAddress({
    required FederationId federationId,
    required ClientHandleArc client,
  });

  Future<List<(String, BigInt, BigInt?)>> getAddresses({
    required FederationId federationId,
  });

  Future<void> monitorAllUnusedPeginAddresses({
    required ArcBTreeMapFederationIdClientHandleArc clients,
  });

  // HINT: Make it `#[frb(sync)]` to let it become the default constructor of Dart class.
  static Future<WalletHandler> newInstance({
    required UnboundedSenderFederationIdTweakIdx monitorTx,
    required TaskGroup taskGroup,
  }) => RustLib.instance.api.crateWalletWalletHandlerNew(
    monitorTx: monitorTx,
    taskGroup: taskGroup,
  );

  Future<void> spawnPeginAddressWatcher({
    required UnboundedReceiverFederationIdTweakIdx monitorRx,
    required ArcBTreeMapFederationIdClientHandleArc clients,
  });
}
